# Generated by Django 6.0.5 on 2026-05-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='join_code',
            field=models.CharField(blank=True, db_index=True, max_length=8, unique=True),
        ),
    ]
