# Generated by Django 6.0.5 on 2026-05-26 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('household', '0003_alter_householdmember_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_individual', models.BooleanField(default=False)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subspaces', to='household.household')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='household.household')),
                ('subspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spaces', to='subspace.subspace')),
            ],
        ),
        migrations.CreateModel(
            name='SubspaceJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subspace_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subspace_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('subspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='subspace.subspace')),
            ],
        ),
        migrations.CreateModel(
            name='SubspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending')], default='active', max_length=10)),
                ('subspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='subspace.subspace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subspace_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('subspace', 'user')},
            },
        ),
    ]
