# Generated by Django 6.0.5 on 2026-05-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_password_reset_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firebase_uid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_reset_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_status',
        ),
        migrations.AddField(
            model_name='user',
            name='status_vibe',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('exam', 'Taking Exam'), ('sick', 'Sick'), ('vacation', 'On Vacation')], default='available', max_length=20),
        ),
    ]
