# Generated by Django 6.0.5 on 2026-05-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_password_reset_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_reset_code',
        ),
    ]
